### ISSUE TITLE
Hope to provide a XposedBridgeApi-86.jar

### ISSUE THREAD

**Issue by qssq** [rovo89/XposedTools#13]
I am a novice, I VPN agent in China led me to download dependent module too long, download this project compiled for a long time are not complete, so can give me a 86 API?

**Comment by rovo89** [comment]
How about doing some research on your own? You keep flooding my GitHub projects with basic, incomplete questions lately, and I'm not willing to spend any more time answering them.

PS: There is no API version 86: https://github.com/rovo89/XposedBridge/wiki/Using-the-Xposed-Framework-API
