### ISSUE TITLE
Support for TouchWiz Lollipop

### ISSUE THREAD

**Issue by surferNayan** [rovo89/XposedTools#3]
Hi,
I am aware of the fact that xposed is only compatible with AOSP ROMs. But I had always been using Samsung mobiles with TouchWiz ROMs. I cannot live without xposed in my mobile. It's just a torture. I want to know if you are already working on bringing support to touchwiz. If yes can you tell me a rough idea as to when I can expect the release(even if it is after a year please mention it, as I can decide whether to update to lollipop or not based on your comment).

Also I am C/C++ developer, but not too great in system programming. If you think it will be easy for others to port xposed for touchwiz, please guide us here.

Thanks a lot for the awesome framework :)

**Comment by surferNayan** [comment]
Any update on this?

**Comment by rovo89** [comment]
There isn't much I can say about this. I have started working on support for Samsung ROMs shortly after the initial alpha release. Some of the differences between their and AOSP's ART variant are already fixed, but the next step would be to unpack .odex.xz files on the fly, which is quite complex. It's unclear which further difference will come up afterwards. So I have no idea when or even if I can add support for their ROMs.

I close this issue here, because this question has nothing to do with the compiler tools.

**Comment by thahim** [comment]
I have asked it many times on different forums, when is it coming, or will it ever be released for samsung lollipop or should we stop waiting?

**Comment by rovo89** [comment]
See above.

**Comment by jkeuclid** [comment]
rovo89, I'm a member of xda (same user name btw) and own a Samsung GS4A SGH-i537 (KK 4.4.2 NH3 towelrooted) and would like to volunteer my services as a tester should you require any and simply thank you for everything you've done to this point and beyond with Xposed which is the main reason I root in the first place, wishing you the best on our behalf.

**Comment by m7oda11** [comment]
i want to know if now will work on my lollipoped galaxy s5 ?

**Comment by Excarius** [comment]
Oh god, come on! Samsung is shit! After S5 i will move from samsung to another brand, like HTC or Sony (but never nexus).
Simply install CM12 CyanogenMod12 5.0.2 Android Lolipop which runs AOSP Android and both XModGames and Xposed framework works. I use alpha3 of xposed, and it works! Got over6-8 modules on, and so far no bootloops. Sometimes it stuck on rebooting bootloops but i just try to reboot again while it is stuck in bootloop and it always, always works! Even if it doesnt, take nandroid backup of ur current original rom and if u dont like cm12, u can anytime restore back to ur original rom.

Cm12 is like owning a google nexus, it has most functions like 4k rcord etc, but no any unique s5 only camera,functions, aaanyway if u want xposed, cm12 is the way u can rest assured.

**Comment by rovo89** [comment]
> i want to know if now will work on my lollipoped galaxy s5 ?

Are you kidding? How hard is it to read a few sentences on this page? For the last time:

**Does it work now?** No. :x: 
**When will it work?** I don't know. :question:
**Will it ever work in the future?** I don't know. :question:
