### ISSUE TITLE
SDK 15 build failed issue

### ISSUE THREAD

**Issue by vivijimmy** [rovo89/XposedTools#5]
Hey guys,

Tried to build SDK 15 but then got the errors below:

Loading config file /home/bruce/XposedTools/build.conf...
Checking requirements...
Expanding targets from 'arm:15'...
  SDK 15, platform arm

Processing SDK 15, platform arm...
Compiling...
Executing: cd /home/bruce/WORKING_DIRECTORY/aosp/4.0.3_r1 && . build/envsetup.sh >/dev/null && lunch full-eng >/dev/null && make -j4 TARGET_CPU_SMP=true xposed libxposed_dalvik
Log: /home/bruce/XposedTools/android/out/sdk15/arm/logs/build_20151231_183447.log
                                            
Build failed!
Last 10 lines from the log:
   cc1plus: warnings being treated as errors
   frameworks/base/cmds/xposed/app_main.cpp: In function 'int main(int, char* const*)':
   frameworks/base/cmds/xposed/app_main.cpp:271: error: will never be executed
   frameworks/base/cmds/xposed/app_main.cpp:272: error: will never be executed
   frameworks/base/cmds/xposed/app_main.cpp: In constructor 'android::AppRuntime::AppRuntime()':
   frameworks/base/cmds/xposed/app_main.cpp:68: error: will never be executed
   make: *** [out/target/product/generic/obj/EXECUTABLES/xposed_intermediates/app_main.o] error 1
   cc1plus: warnings being treated as errors
   frameworks/base/cmds/xposed/xposed_service.cpp:641: error: unused parameter 'allowIsolated'
   make: *** [out/target/product/generic/obj/EXECUTABLES/xposed_intermediates/xposed_service.o] error 1

Then I tried to change the 2 files below, but still not working:

Host_linux-x86.mk
#HOST_GLOBAL_CFLAGS += -D_FORTIFY_SOURCE=0
HOST_GLOBAL_CFLAGS += -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0

Android.mk
#local_cflags_for_slang := -Wno-sign-promo -Wall -Wno-unused-parameter -Werror
local_cflags_for_slang := -Wno-sign-promo -Wall -Wno-unused-parameter

Still I saw the exactly same error.

Any idea what is wrong with this?

**Comment by rovo89** [comment]
That's not really surprising. From my latest official [post](http://forum.xda-developers.com/showpost.php?p=64365859&postcount=27):

> It seems that some vendors have ported a change that was originally made in 5.1 back to 4.4 (KitKat). Xposed currently doesn't work with such ROMs. Why isn't this fixed yet? Well, I have completely restructured the source code and installation procedures for ART on Lollipop. Even though I kept Dalvik in mind, it will still require much more work and testing. Therefore, I'm not able to release pre-Lollipop files at the moment and due to the focus on Lollipop/Marshmallow, I don't think this will change for the next weeks or maybe even months.

The whole framework is currently not meant to be built for Android < 5.0. I hope I can even make it build for ICS again, but if it's requires too much effort, I might drop support for it as most users are probably on a newer ROM.

As this is more a mid- to long-term tasks, I close this issue for now.

**Comment by vivijimmy** [comment]
Just for your information, it seems from 16 to 19 the framework works just fine. The only needed and only version that I am having issue with is SDK 15. Anyway thanks for your great work.

**Comment by vivijimmy** [comment]
Is there any other known method to resolve SDK 15, instead of using your framework?

**Comment by rovo89** [comment]
That's indeed nice to hear. I had roughly tested Xposed using the completely new way 1.5 years ago when I did these changes, but I would generally consider it as "not ready for public" at this time.

I didn't understand your second comment. It reads like "can I use the [Xposed] framework with the [Xposed] framework". Anyway, no, I don't know any other way. I suggest that you simply exclude SDK15 from your tests.
