### ISSUE TITLE
Full AOSP source to build XPOSED?

### ISSUE THREAD

**Issue by al3xv3gas** [rovo89/XposedTools#9]
Do I need to download the full AOSP source to build XPosed from source??? Im kinda confused about this point.

**Comment by rovo89** [comment]
Yes, like mentioned in the readme you need the full AOSP source code.

**Comment by al3xv3gas** [comment]
That's a pain for people like me who want to build a custom version of Xposed! How inefficient is that??? Any suggestions on how to bypass downloading aosp source? @rovo89

**Comment by CorruptComputer** [comment]
Don't be lazy? Like this really isn't an issue. Xposed integrates deeply within android so you really can't get around having to download it.

**Comment by rovo89** [comment]
It's not my fault and I can't change this. Big parts of Xposed modified ART libraries and app_process binaries, both are based on AOSP and obviously have deep dependencies to many other AOSP projects. You will also notice this when you start to build Xposed (or even just the original AOSP ART), it will compile many other prerequisites.

I would love to avoid these huge downloads and especially the disk space, but I can't. The only thing I do to reduce the space needed is using `-g default,platform-linux,-device,-darwin,-cts` for `repo init`. The first two the defaults, and I ask it not to sync projects with groups `device`, `darwin` and `cts` in the `manifest.xml`.

**Comment by al3xv3gas** [comment]
Ok, didn't know that. No it's a huge issue for me. Seeing as I am not able to run Linux on my PC and I do want to build Xposed for myself. But anyways thanks for all the info! Will look for a way!;) Xposed is really really awesome btw! @rovo89
